# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tercer_Hito' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Database'
  # Pods for Tercer_Hito

  target 'Tercer_HitoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tercer_HitoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
